name: Lint Python Files
description: Lint Python files using Pylint

runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Setting up Python 3.11
    uses: actions/setup-python@v3
    with:
      python-version: 3.11

  - name: Installing Pylint
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install pylint

  - name: Add action_path to $GITHUB_PATH
    run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash

  - name: Running Pylint
    shell: bash
    run: entrypoint.sh
